config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users do
    resource :profile
  end
  resources :contacts
  resources :donates
  get '/about' => 'pages#about'
  root 'pages#home'
end

app/models/contact.rb
class Contact < ActiveRecord::Base
  validates :name, presence: true
  validates :email, presence: true
end

app/models/plan.rb
class Plan < ActiveRecord::Base
  has_many :users
end

app/models/profile.rb
class Profile < ActiveRecord::Base
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  belongs_to :plan
  has_one :profile
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def new
    @contact = Contact.new
  end

  def create
    @contact = Contact.new(contact_params)

    if @contact.save
      name = params[:contact][:name]
      email = params[:contact][:email]
      body = params[:contact][:comments]
      ContactMailer.contact_email(name, email, body).deliver
      flash[:success] = 'Message sent.'
      redirect_to new_contact_path
    else
      flash[:danger] = 'Error occurred. message has not been sent.'
      redirect_to new_contact_path
    end

  end


  private
  def contact_params
    params.require(:contact).permit(:name, :email, :comments)
  end
end

app/controllers/donates_controller.rb
class DonatesController < ApplicationController
  def new
  end

  def create
    # Amount in cents
    @amount = 500

    customer = Stripe::Customer.create(
      :email => 'example@stripe.com',
      :card  => params[:stripeToken]
    )

    charge = Stripe::Charge.create(
      :customer    => customer.id,
      :amount      => @amount,
      :description => 'Micro Donate',
      :currency    => 'usd'
    )

  rescue Stripe::CardError => e
    flash[:error] = e.message
    redirect_to users_path
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @signup = Plan.find(1)
    @donate = Plan.find(2)
  end

  def about
  end
  def edit

  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :authenticate_user!
  before_action :only_current_user

  def new
    # form for each user to fill out there own profile
    @user = User.find(params[:user_id])
    @profile = Profile.new
  end

  def create
    @user = User.find(params[:user_id])
    @profile = @user.build_profile(profile_params)
    if @profile.save
      flash[:success]='Profile Updated'
      redirect_to user_path(params[:user_id])
    else
      flash[:error]='Profile Not Created'
      render action: :new
    end
  end

  def edit
    @user = User.find(params[:user_id])
    @profile = @user.profile
  end

  def update
    @user = User.find(params[:user_id])
    @profile = @user.profile
    if @profile.update_attributes(profile_params)
      flash[:success] = 'Profile Updated!'
      redirect_to user_path(params[:user_id])
    else
      flash[:error] = 'Profile Not Updated'
      render action: :edit
    end
  end
end

private
def profile_params
  params.require(:profile).permit(:first_name, :last_name, :contact_email, :description, :need)
end

def only_current_user
  @user = User.find(params[:user_id])
  redirect_to(root_url) unless @user == current_user
end

app/controllers/users_controller.rb
class UsersController < ApplicationController


  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/donates_helper.rb
module DonatesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/contacts/new.html.erb
<div class="row">
  <div class="col-md-4 col-md-offset-4">
    <div class="well">
      <%= form_for @contact do |f| %>
        <div class="form-group">
          <%= f.label :name %>
          <%= f.text_field :name, class: 'form-control' %>
        </div>
        <div class="form-group">
          <%= f.label :email %>
          <%= f.email_field :email, class: 'form-control' %>
        </div>
        <div class="form-group">
          <%= f.label :comments %>
          <%= f.text_area :comments, class: 'form-control' %>
        </div>
        <%= f.submit 'Submit', class: 'btn btn-default' %>
      <% end %>
    </div>
  </div>
</div>

app/views/donates/create.html.erb
<meta HTTP-EQUIV="REFRESH" content="5; url=<%= users_path %>">
<div class="jumbotron">
  <div class="text-center">
    <h2>Thank you for your <strong>$5.00</strong> donation!</h2>
    <%= image_tag 'cheering.gif' %>
  </div>
</div>

app/views/donates/new.html.erb
<%= form_tag donates_path do %>
  <article>
    <label class="amount white-text">
      <span>Donation: $5.00</span>
    </label>
  </article>

  <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
          data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
          data-description="Paying It Forward"
          data-amount="500"
          data-locale="auto"></script>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Micro Donate</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>
<nav class="navbar navbar-default navbar-static-top" role="navigation">
  <div class='container'>
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#main-nav-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to root_path, class: "navbar-brand" do %>
        <i class="fa fa-share-alt-square"></i>
        Micro Donate
      <% end %>
    </div>
    <div class="collapse navbar-collapse" id="main-nav-collapse">
      <div class="nav navbar-nav navbar-right">
        <%= link_to 'Donate', users_path, class: 'btn btn-success navbar-btn', method: :get %>
        <% if current_user %>
          <%= button_to 'Log Out', destroy_user_session_path, method: :delete, class: 'btn btn-primary navbar-btn' %>
        <% else %>
          <%= link_to 'Log In', new_user_session_path, class: 'btn btn-primary navbar-btn', method: :get %>
        <% end %>
      </div>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to 'About', about_path %></li>
        <li><%= link_to 'Contact Us', new_contact_path %></li>
      </ul>
    </div>
  </div>
</nav>
<div class="container">
  <% flash.each do |key, value| %>
    <%= content_tag :div, value, class: "alert alert-#{key}" %>
  <% end %>
  <%= yield %>
</div>

</body>
</html>

app/views/pages/about.html.erb
<div class="container">
<h2 class="white-text text-center">About Us</h2>
  <p class="white-text text-center">
    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec iaculis, mauris nec aliquet gravida,
    libero est iaculis purus, at blandit ex ligula vel mi.
    Pellentesque porttitor hendrerit turpis et mollis. Cras rhoncus tempor mi id mattis. Fusce placerat,
    ipsum quis egestas sagittis, enim magna dapibus sapien,
    nec aliquet diam urna a odio. Aenean a massa vitae lectus suscipit fringilla ullamcorper eget enim.
    Curabitur posuere sapien velit, quis suscipit orci venenatis nec.
    Vivamus vestibulum finibus felis vel maximus. Etiam commodo dictum egestas.
  </p>
  <p class="white-text text-center">
    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec iaculis, mauris nec aliquet gravida,
    libero est iaculis purus, at blandit ex ligula vel mi.
    Pellentesque porttitor hendrerit turpis et mollis. Cras rhoncus tempor mi id mattis. Fusce placerat,
    ipsum quis egestas sagittis, enim magna dapibus sapien,
    nec aliquet diam urna a odio. Aenean a massa vitae lectus suscipit fringilla ullamcorper eget enim.
    Curabitur posuere sapien velit, quis suscipit orci venenatis nec.
    Vivamus vestibulum finibus felis vel maximus. Etiam commodo dictum egestas.
  </p>
  <p class="white-text text-center">
    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec iaculis, mauris nec aliquet gravida,
    libero est iaculis purus, at blandit ex ligula vel mi.
    Pellentesque porttitor hendrerit turpis et mollis. Cras rhoncus tempor mi id mattis. Fusce placerat,
    ipsum quis egestas sagittis, enim magna dapibus sapien,
    nec aliquet diam urna a odio. Aenean a massa vitae lectus suscipit fringilla ullamcorper eget enim.
    Curabitur posuere sapien velit, quis suscipit orci venenatis nec.
    Vivamus vestibulum finibus felis vel maximus. Etiam commodo dictum egestas.
  </p>
</div>

app/views/pages/home.html.erb
<div class="jumbotron text-center">
  <h1>Welcome to Micro Donate</h1>

  <h3>Helping any way we can!</h3>
</div>
<div class="row text-center">
  <% if user_signed_in? %>
    <div class="col-md-6">
      <div class="well">
        <% if current_user.profile %>
          <h2>Your Profile</h2>
          <%= link_to 'Edit Your Profile', edit_user_profile_path(current_user.id), class: 'btn btn-default btn-lg btn-block' %>
          <%= link_to 'View Your Profile', user_path(current_user.id), class: 'btn btn-default btn-lg btn-block' %>
        <% else %>
          <%= link_to "Create Your Profile", new_user_profile_path(current_user) if current_user %>
        <% end %>
      </div>
    </div>
    <div class="col-md-6">
      <div class="well">
        <h2>The Community</h2>
        <%= link_to 'Visit The Community', users_path, class: 'btn btn-default btn-lg btn-block' %>
      </div>
    </div>
  <% else %>
    <div class="col-md-6">
      <div class="white-text">
        <h2>Need Help?</h2>
        <h4>Looking for a little help</h4>
        <%= link_to "Sign Up", new_user_registration_path(plan: @signup), class: 'btn btn-primary btn-lg btn-block' %>
      </div>
    </div>
    <div class="col-md-6">
      <div class="white-text">
        <h2>Want to donate?</h2>
        <h4>If you're looking to give a little help</h4>
        <%= link_to "Donate", users_path, class: 'btn btn-success btn-lg btn-block' %>
      </div>
    </div>
  <% end %>
</div>

app/views/profiles/_form.html.erb
<%= form_for @profile, url: user_profile_path do |f| %>
  <div class="form-group">
    <%= f.label :first_name %>
    <%= f.text_field :first_name, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :last_name %>
    <%= f.text_field :last_name, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :contact_email %>
    <%= f.text_field :contact_email, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label 'About Yourself' %>
    <%= f.text_area :description, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :need %>
    <%= f.text_area :need, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.submit "Update Profile", class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/profiles/edit.html.erb
<div class="row">
  <div class="col-md-6 col-md-offsett-6">
    <h1 class="text-center white-text">
      Update Your Profile
    </h1>

    <p class="text-center white-text">
      Become a part of a helping community!
    </p>

    <div class="well">
      <%= render 'form' %>
    </div>
  </div>
</div>

app/views/profiles/new.html.erb
<div class="row">
  <div class="col-md-6 col-md-offsett-6">
    <h1 class="text-center">
      Create Your Profile
    </h1>

    <p class="text-center">
      Become a part of a helping community!
    </p>

    <div class="well">
      <%= form_for @profile, url: user_profile_path do |f| %>
        <div class="form-group">
          <%= f.label :first_name %>
          <%= f.text_field :first_name, class: 'form-control' %>
        </div>
        <div class="form-group">
          <%= f.label :last_name %>
          <%= f.text_field :last_name, class: 'form-control' %>
        </div>
        <div class="form-group">
          <%= f.label :contact_email %>
          <%= f.text_field :contact_email, class: 'form-control' %>
        </div>
        <div class="form-group">
          <%= f.label 'About Yourself' %>
          <%= f.text_area :description, class: 'form-control' %>
        </div>
        <div class="form-group">
          <%= f.label :need %>
          <%= f.text_area :need, class: 'form-control' %>
        </div>
        <div class="form-group">
          <%= f.submit "Update Profile", class: 'btn btn-primary' %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<div class="row">
  <div class="container">
    <% @users.each do |user| %>
      <% if user.profile %>
        <div class="col-md-4">
          <div class="well">
          <ul class="list-unstyled text-center">
            <li><strong>Need</strong></li>
            <li><%= user.profile.need %></li>
            <li class="text-right"><%= link_to 'Donate', new_donate_path, class: 'btn btn-success', method: :get %></li>
          </ul>
          </div>
        </div>
      <% end %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <div class="well text-center">
        <h2><%= @user.profile.first_name %>
          <%= @user.profile.last_name %>
        </h2>

        <p class="text-left">
          <%= @user.profile.description %>
        </p>
        <h4>Need</h4>

        <p class="text-left">
          <%= @user.profile.need %>
        </p>
      </div>
    </div>
  </div>
</div>